apiVersion: v1
kind: ConfigMap
metadata:
  name: port-config
  namespace: nginx-ingress 
data:
  insertedd.yml: |+
        upstream default-springboot-ingress-consumer.mariusdev.net-kafka-demo-consumer-80 {
            zone default-springboot-ingress-consumer.mariusdev.net-kafka-demo-consumer-80 256k;
            random two least_conn;

            server 10.233.90.25:8091 max_fails=1 fail_timeout=10s max_conns=0;

    }
    upstream default-springboot-ingress-consumer.mariusdev.net-kafka-demo-producer-80 {
            zone default-springboot-ingress-consumer.mariusdev.net-kafka-demo-producer-80 256k;
            random two least_conn;

            server 10.233.90.28:8090 max_fails=1 fail_timeout=10s max_conns=0;

    }
    upstream default-springboot-ingress-kafdrop.mariusdev.net-kafka-demo-producer-80 {
            zone default-springboot-ingress-kafdrop.mariusdev.net-kafka-demo-producer-80 256k;
            random two least_conn;

            server 10.233.90.28:8090 max_fails=1 fail_timeout=10s max_conns=0;

    }
    upstream default-springboot-ingress-producer.mariusdev.net-kafka-demo-producer-80 {
            zone default-springboot-ingress-producer.mariusdev.net-kafka-demo-producer-80 256k;
            random two least_conn;

            server 10.233.90.28:8090 max_fails=1 fail_timeout=10s max_conns=0;

    }


    server {


            listen 80;








            server_tokens on;

            server_name consumer.mariusdev.net;

            set $resource_type "ingress";
            set $resource_name "springboot-ingress";
            set $resource_namespace "default";







            location /kafkaproduce {
                    set $service "kafka-demo-producer";


                    proxy_http_version 1.1;


                    proxy_connect_timeout 60s;
                    proxy_read_timeout 60s;
                    proxy_send_timeout 60s;
                    client_max_body_size 1m;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_buffering on;

                    proxy_pass http://default-springboot-ingress-consumer.mariusdev.net-kafka-demo-producer-80;


            }
            location /kafkaconsume(/|$)(.*) {
                    set $service "kafka-demo-consumer";


                    proxy_http_version 1.1;


                    proxy_connect_timeout 60s;
                    proxy_read_timeout 60s;
                    proxy_send_timeout 60s;
                    client_max_body_size 1m;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_buffering on;

                    proxy_pass http://default-springboot-ingress-consumer.mariusdev.net-kafka-demo-consumer-80;


            }


    }
    server {


            listen 80;








            server_tokens on;

            server_name producer.mariusdev.net;

            set $resource_type "ingress";
            set $resource_name "springboot-ingress";
            set $resource_namespace "default";







            location / {
                    set $service "kafka-demo-producer";


                    proxy_http_version 1.1;


                    proxy_connect_timeout 60s;
                    proxy_read_timeout 60s;
                    proxy_send_timeout 60s;
                    client_max_body_size 1m;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_buffering on;

                    proxy_pass http://default-springboot-ingress-producer.mariusdev.net-kafka-demo-producer-80;


            }


    }
    server {


            listen 80;








            server_tokens on;

            server_name kafdrop.mariusdev.net;

            set $resource_type "ingress";
            set $resource_name "springboot-ingress";
            set $resource_namespace "default";







            location / {
                    set $service "kafka-demo-producer";


                    proxy_http_version 1.1;


                    proxy_connect_timeout 60s;
                    proxy_read_timeout 60s;
                    proxy_send_timeout 60s;
                    client_max_body_size 1m;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_buffering on;

                    proxy_pass http://default-springboot-ingress-kafdrop.mariusdev.net-kafka-demo-producer-80;


            }


    }