apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2022-01-15T11:59:06Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  name: data-my-release-kafka-0
  namespace: default
  resourceVersion: "85239"
  uid: b5474d83-47ae-47f8-875c-fbc910fceba2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem