apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  local:
    path: /home/vagrant/data/pv/elasticsearch-master-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
