apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  local:
    path: /home/vagrant/data/pv/clickhouse-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
