apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: clickhouse-storage-dir-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: clickhouse-pv #only use exactly this pv
