apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-demo-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-demo-consumer
  template:
    metadata:
      labels:
        app: kafka-demo-consumer
    spec:
      containers:
        - name: kafka-demo-consumer
          image: mariuss97/kafka-demo-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: PORT
              value: "8091"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-demo-consumer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8091
      #nodePort: 30001
  selector:
    app: kafka-demo-consumer