apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kafka-consumer
build:
  artifacts:
  - image: mariuss97/kafka-demo-consumer
    jib: {}
  local: {}
  
deploy:
  kubectl:
    manifests:
    - k8s-kafka-demo-consumer-deployment.yml
