apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: marius.demo
    http:
      paths:
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: kafka-demo-consumer
            port:
              number: 80