apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /home/vagrant/data/pv/kafka-pv