apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-opcua-server
  namespace: harbor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-opcua-server
  template:
    metadata:
      labels:
        app: node-opcua-server
    spec:
      containers:
        - name: node-opcua-server
          image: 100.0.0.2:30090/library/mylittleopcua:latest
          #imagePullPolicy: Always
          ports:
            - containerPort: 4334
          env:
            - name: PORT
              value: "4334"
            - name: RESOURCEPATH
              value: "/UA/MyLittleServer"
            - name: OPCUAHOSTNAME
              value: "172.17.0.1"
      imagePullSecrets:
        - name: regcred   
---
apiVersion: v1
kind: Service
metadata:
  name: node-opcua-server
spec:
  type: ClusterIP
  ports:
    - port: 4334
      targetPort: 4334
      #nodePort: 30000
  selector:
    app: node-opcua-server
