apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: elk
data:
  fluent-bit.conf: |
  
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Tag kube.*
    Parser docker
    Exclude_Path /var/log/containers/*_my_java_apps_*.log
    Mem_Buf_Limit 10MB
    Skip_Long_Lines Off

[FILTER]
    Name kubernetes
    Match kube.*
    Merge_Log On
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[OUTPUT]
    name            es
    match           *
    host            elasticsearch
    port            9200
    replace_dots    on
    retry_limit     false
    logstash_format on
    logstash_prefix fluent-bit
    HTTP_User       elastic
    HTTP_Passwd     changeme
    Index fluent_bit
    Type cpu_metrics
    Suppress_Type_Name On