apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-database2-pv
  namespace: harbor-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  local:
    path: /home/vagrant/data/pv/harbor-database2-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1